### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by whyintheworld** [ethayer/lock-manager#3] opened 2017-02-11 13:35 UTC
The current setup always notifies me, but I'd like to customize that so that if my wife is home, or certain modes are active that it wouldn't send the notification.  This would be adding constraints to the notify options.

**Comment by ethayer** [comment] 2017-03-10 06:35
I'm going to close this as a duplicate of https://github.com/ethayer/lock-manager/issues/1

**Closed by ethayer** 2017-03-10 06:35 UTC
Labels: duplicate, enhancement
